// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzpzmdsqrrtlrwlwqhmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6cHptZHNxcnJ0bHJ3bHdxaG1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MzEzMTIsImV4cCI6MjA2NjIwNzMxMn0.MbivHf12vf95jgSaD2yz0p5TOgSb02a8TYMbLInC8W0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);